@startuml
'https://plantuml.com/sequence-diagram
'================== HECHOS ==================
class Hecho {
    - titulo: String
    - descripcion: String
    - categoria: Categoria
    - ubicacion: Ubicacion
    - fechaDeAcontecimiento: DateTime
    - fechaDeCarga: DateTime
}

'================ Categoria ================
class Categoria {
    - nombre: String
}

'================ UBICACION ================
class Ubicacion {
    - latitud: Long
    - longitud: Long
}

'================ ADAPTADOR ================
interface IServicioExternoAdapter {
    +obtenerHechos():List<HechoOutputDTO>
}

class DesastresNaturalesAdapter {
  - webClientAdaptado: DesastresNaturales
  + obtenerHechos(): List<HechoOutputDTO>
}

class DesastresNaturales {
  - webClient: WebClient
  + obtenerHechosDeAPI(): List<HechoOutputDTO>
}

'================== RELACIONES ==================
Hecho --> Ubicacion
Hecho --> Categoria

DesastresNaturalesAdapter ..|> IServicioExternoAdapter
DesastresNaturalesAdapter --> DesastresNaturales
@enduml