@startuml
'https://plantuml.com/class-diagram

FuenteEstatica --> Hecho
Coleccion --> Fuente
Coleccion o--> Hecho
Hecho --> Categoria
Hecho --> Origen
Hecho --> Contribuyente
UsuarioRegistrado ..|> Contribuyente
Administrador ..|> Contribuyente
Administrador --> Coleccion
SolicitudDeEliminacion *-- Hecho
Administrador -> SolicitudDeEliminacion
UsuarioRegistrado -> SolicitudDeEliminacion
ImportadorDeArchivosCSV ..|> ImportadorDeArchivos
FuenteEstatica --> ImportadorDeArchivos
Coleccion --> CriterioDePertenencia
CriterioPorFecha ..> CriterioDePertenencia
CriterioPorCategoria ..> CriterioDePertenencia
CriterioPorUbicacion ..> CriterioDePertenencia
Hecho --> Ubicacion
Hecho--> Etiqueta
FuenteEstatica ..> Fuente
SolicitudDeEliminacion --> EstadoDeSolicitud
HechosEliminados --> Hecho
SolicitudDeEliminacion --> HechosEliminados




'--------- File: Contenido ---------
class Coleccion {
    - titulo: String
    - descripcion: String
    - hechos : List<Hecho>
    - fuenteDeHechos : Fuente
    - criteriosDePertenencia : List<CriterioDePertenencia>

    + cargarHechos() : void
}

class Etiqueta {
    - nombre: String
}

class Hecho {
    - titulo: String
    - descripcion: String
    - categoria: Categoria
    - ubicacion: Ubicacion
    - contenido: ContenidoMultimedia
    - fechaDeAcontecimiento: DateTime
    - fechaDeCarga: DateTime
    - origen: Origen
    - etiquetas: List<Etiqueta>
    - visible: Bool
}

class HechosEliminados {
   - hechosEliminados: List<Hecho>
   + agregarHecho(Hecho hechoEliminado): void
}

'Enum porque no tiene comportamiento, y necesitamos evitar inconsistencia
enum Origen {
    ARCHIVO
    CONTRIBUYENTE
}

class Ubicacion{
    - latitud: Int
    - longitud: Int
    - lugar: String
}


'--------- File: Criterio ---------

'Por consistencia de datos
class Categoria {
    - nombre: String
}

interface CriterioDePertenencia {
    + hechoLoCumple(Hecho unoHecho): bool
}

class CriterioPorCategoria {
    - categoriaACumplir: Categoria

    + hechoLoCumple(Hecho unoHecho): bool
}

class CriterioPorFecha {
    - fechaACumplir: LocalDateTime

    + hechoLoCumple(Hecho unoHecho): bool
}

class CriterioPorUbicacion {
    - ubicacion: Ubicacion

    + hechoLoCumple(Hecho unoHecho): bool
}


'--------- File: Fuente ---------

interface Fuente {
    + obtenerHechos():  List<Hecho>
}

class FuenteEstatica {
    - importadorDeArchivos: ImportadorDeArchivos
    - archivoDeHechos: File

    + obtenerHechos(): List<Hecho>
}

interface ImportadorDeArchivos {
    + importarHechos(File unArchivo): List<Hecho>
}

class ImportadorDeArchivosCSV {
     + importarHechos(File unArchivo): List<Hecho>
}


'--------- File: Solicitud ---------

enum EstadoDeSolicitud {
    RECHAZADA
    ACEPTADA
    PENDIENTE
}

class SolicitudDeEliminacion {
    - hecho: Hecho
    - descripcion: String
    - estadoDeSolicitud: EstadoDeSolicitud
    - fechaDeCreacion: DateTime

    + aceptarSolicitud(): void
    + rechazarSolicitud(): void
}


'--------- File: Usuario ---------

class Administrador {
}

interface Contribuyente {
}

class UsuarioRegistrado {
    - nombre: String
    - apellido: String
    - edad: int
}

class Visualizador {
}

@enduml

