@startuml
'https://plantuml.com/class-diagram

FuenteEstatica --> Hecho
Coleccion ..> FuenteEstatica
Coleccion o--> Hecho
Hecho --> Categoria
Hecho --> Origen
Hecho --> Contribuyente
UsuarioRegistrado ..|> Contribuyente
Administrador ..|> Contribuyente
Administrador --> Coleccion
SolicitudDeEliminacion --> Hecho
SolicitudDeEliminacion --> EstadoSolicitud
Administrador -> SolicitudDeEliminacion
UsuarioRegistrado -> SolicitudDeEliminacion
ImportadorDeArchivosCSV ..|> ImportadorDeArchivos
FuenteEstatica --> ImportadorDeArchivos
Coleccion --> CriterioDePertenencia
CriterioPorFecha ..> CriterioDePertenencia
CriterioPorCategoria ..> CriterioDePertenencia
CriterioPorUbicacion ..> CriterioDePertenencia
Hecho --> Ubicacion
Hecho--> Etiqueta

class Hecho {
    - titulo: String
    - descripcion: String
    - categoria: Categoria
    - ubicacion: Ubicacion
    - contenido: ContenidoMultimedia
    - fechaDeAcontecimiento: DateTime
    - fechaDeCarga: DateTime
    - origen: Origen
    - etiquetas: List<Etiqueta>
    - visible: Bool
}

class Etiqueta {
    - nombre: String
}

class Ubicacion{
    - nombreLugar: String
    - descripcion: String
    - longitud: Int
    - latitud: Int
}

'Enum porque no tiene comportamiento, y necesitamos evitar inconsistencia
enum Origen {
    ARCHIVO
    CONTRIBUYENTE
}

'Por consistencia de datos
class Categoria {
    - nombre: String
}

class SolicitudDeEliminacion {
    - texto: String
    - hechoAEliminar: Hecho

    + aceptar(): void
    + rechazar(): void
}

enum EstadoSolicitud {
    RECHAZADA
    ACEPTADA
    PENDIENTE
}

interface Fuente {
    + obtenerHechos(File unArchivo): Hecho
}

class FuenteEstatica {
    + obtenerHechos(File unArchivo): Hecho
}

class Coleccion {
    - titulo: String
    - descripcion: String
    - hechos : List<Hecho>
    - fuenteDeHechos : Fuente
    - criteriosDePertenencia : List<CriterioDePertenencia>

    + cargarHechos() : void
}

'VER
interface CriterioDePertenencia {
    + hechosQueLoCumplen(List<Hecho> unosHechos): List<Hecho> otrosHechos
}

class CriterioPorFecha {
    - fechaACumplir: LocalDateTime

    + hechosQueLoCumplen(List<Hecho> unosHechos): List<Hecho> otrosHechos
}

class CriterioPorCategoria {
    - categoriaACumplir: Categoria

    + hechosQueLoCumplen(List<Hecho> unosHechos): List<Hecho> otrosHechos
}

class CriterioPorUbicacion {
    - ubicacion: Ubicacion

    + hechosQueLoCumplen(List<Hecho> unosHechos): List<Hecho> otrosHechos
}

interface Contribuyente {
    + subirHecho()
}

class Administrador {
    -nombre: String
}

class Visualizador {

}

class UsuarioRegistrado {
    -nombre: String
    -apellido: String
    -edad: int

}

interface ImportadorDeArchivos {
    + importarHechos(File unArchivo): Hecho
}

class ImportadorDeArchivosCSV {
     + importarHechos(File unArchivo): Hecho
}

@enduml

